# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    environment:
      IMAGE: lodaidelima/dockerapp
      TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $IMAGE
          tag: $TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $IMAGE
          tag: $TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  sample: 
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
